import { Meteor } from 'meteor/meteor';

// institutional
export const ORGANIZATION_NAME = Meteor.settings.public.Collective.name;
export const ORGANIZATION_ID = Meteor.settings.public.Collective._id;

// text
export const $LANGUAGE = 'en'; // language of the app

// rules
export const rules = {
  TITLE_MAX_LENGTH: 100, // length of contract titles
  MAX_TAGS_PER_CONTRACT: 6, // max amount of tags per contract
  MIN_TAGS_PER_CONTRACT: 1, // min amount.
  MAX_PROFILE_NAME_LENGTH: 20, // Maximum extension of profile name
  VOTES_INITIAL_QUANTITY: 100, // initial votes for genesis transaction event
};

// ui
export const gui = {
  MIN_AGORA_WIDTH: 360, // pixel min width for agora when resizing
  MIN_CONTRACT_WIDTH: 360, // pix min width for contract when resizing
  SIDEBAR_WIDTH: 320, // width of sidebar
  DESKTOP_MIN_WIDTH: 992, // min width of desktop view in pixels (connected to CSS)
  MOBILE_MAX_WIDTH: 768, // max width of mobile screens
};

// timers
export const timers = {
  SERVER_INTERVAL: 500,  // time in ms to communicate with server for contenteditable stuff.
  ANIMATION_DURATION: 250, // pace of animations
  WARNING_DURATION: 5000, // duration of warning messages
};

/**
NOTE: commented before erasing in case there are still being used somewhere in the code.

// classes
OFFSCREEN_CLASS = 'off-screen';

// key strings
CURRENCY_BITCOIN = 'BITCOIN';
CURRENCY_SATOSHI = 'SATOSHI';
CURRENCY_VOTES = 'VOTES';
ENTITY_INDIVIDUAL = 'INDIVIDUAL';
ENTITY_COLLECTIVE = 'COLLECTIVE';
ENTITY_CONTRACT = 'CONTRACT';
ENTITY_UNKNOWN = 'UNKNOWN';
KIND_VOTE = 'VOTE';
KIND_DELEGATION = 'DELEGATION';
KIND_MEMBERSHIP = 'MEMBERSHIP';
KIND_UNKNOWN = 'UNKNOWN';
KIND_DRAFT = 'DRAFT';
TRANSACTION_STATUS_PENDING = 'PENDING';
TRANSACTION_STATUS_REJECTED = 'REJECTED';
TRANSACTION_STATUS_CONFIRMED = 'CONFIRMED';
ROLE_DELEGATOR = 'DELEGATOR';
ROLE_DELEGATE = 'DELEGATE';
ROLE_AUTHOR = 'AUTHOR';
ROLE_ENDORSER = 'ENDORSER';
STAGE_DRAFT = 'DRAFT';
STAGE_LIVE = 'LIVE';
STAGE_FINISH = 'FINISH';
THREAD_ACTION_COMMENT = 'COMMENT';
THREAD_ACTION_VOTE = 'VOTE';
THREAD_ACTION_SORT = 'SORT';
THREAD_ACTION_REPLY = 'REPLY';
THREAD_STATUS_NEW = 'NEW';
THREAD_STATUS_VERIFIED = 'VERIFIED';
THREAD_STATUS_PROCESSED = 'PROCESSED';
WALLET_MODE_PENDING = 'PENDING';
WALLET_MODE_EXECUTED = 'EXECUTED';
SIGNATURE_STATUS_PENDING = 'PENDING';
SIGNATURE_STATUS_REJECTED = 'REJECTED';
SIGNATURE_STATUS_CONFIRMED = 'CONFIRMED';
EXECUTION_STATUS_OPEN = 'OPEN';
EXECUTION_STATUS_APPROVED = 'APPROVED';
EXECUTION_STATUS_ALTERNATIVE = 'ALTERNATIVE'
EXECUTION_STATUS_REJECTED = 'REJECTED';
EXECUTION_STATUS_VOID = 'VOID';
CONTEXT_GLOBAL = 'GLOBAL';
CONTEXT_LOCAL = 'LOCAL';
URL_STATUS_VERIFY = 'VERIFY';
URL_STATUS_UNAVAILABLE = 'UNAVAILABLE';
URL_STATUS_AVAILABLE = 'AVAILABLE';
URL_STATUS_NONE = 'NONE';
BALLOT_OPTION_MODE_AUTHORIZE = 'AUTHORIZE';
BALLOT_OPTION_MODE_REJECT = 'REJECT';
BALLOT_OPTION_MODE_FORK = 'FORK';
BALLOT_OPTION_MODE_NONE = 'NONE';
ANONYMOUS = '0000000';

//feeds
FEED_VOTE_DRAFT_PEER = 'CUSTOM PEER DRAFTS';
FEED_VOTE_DRAFT = 'vote-drafts';
FEED_DELEGATION_DRAFT_PEER = 'CUSTOM PEER DELEGATION DRAFTS';
FEED_DELEGATION_DRAFT = 'DELEGATION DRAFTS';
FEED_MEMBERSHIP_DRAFT_PEER = 'CUSTOM PEER MEMBERSHIP DRAFT';
FEED_MEMBERSHIP_DRAFT = 'MEMBERSHIP DRAFTS';
FEED_DRAFTS = 'ALL DRAFTS';

FEED_VOTE_LIVE_PEER = 'live-votes-peer';
FEED_VOTE_LIVE = 'live-votes';
FEED_DELEGATION_LIVE_PEER = 'CUSTOM PEER DELEGATION SENT';
FEED_DELEGATION_LIVE = 'LIVE DELEGATIONS';
FEED_MEMBERSHIP_LIVE_PEER = 'CUSTOM PEER MEMBERSHIP REQUEST';
FEED_MEMBERSHIP_LIVE = 'LIVE MEMBERSHIPS';
FEED_LIVE = 'ALL LIVE';

FEED_VOTE_FINISH_APPROVED = 'votes-finish-approved';
FEED_VOTE_FINISH_REJECTED = 'votes-finish-rejected';
FEED_VOTE_FINISH_ALTERNATIVE = 'VOTES FINISH ALTERNATIVE';
FEED_VOTE_FINISH = 'ALL VOTES FINISH';
FEED_DELEGATION_FINISH_APPROVED = 'CONFIRMED DELEGATIONS';
FEED_DELEGATION_FINISH_REJECTED = 'REJECTED DELEGATIONS';
FEED_DELEGATION_FINISH = 'ALL DELEGATIONS';
FEED_MEMBERSHIP_FINISH_APPROVED = 'APPROVED MEMBERSHIPS';
FEED_MEMBERSHIP_FINISH_REJECTED = 'REJECTED MEMBERSHIPS';
FEED_MEMBERSHIP_FINISH = 'ALL CONFIRMED MEMBERSHIPS';
FEED_FINISH = 'ALL FINISH';

FEED_VOTE_FINISH_APPROVED_PEER = 'CUSTOM PEER APPROVED VOTES';
FEED_VOTE_FINISH_REJECTED_PEER = 'CUSTOM PEER REJECTED VOTES';
FEED_VOTE_FINISH_ALTERNATIVE_PEER = 'CUSTOM PEER ALTERNATIVE VOTES';
FEED_DELEGATION_FINISH_APPROVED_PEER = 'CUSTOM PEER APPROVED DELEGATIONS';
FEED_DELEGATION_FINISH_REJECTED_PEER = 'CUSTOM PEER REJECTED DELEGATIONS';
FEED_MEMBERSHIP_FINISH_APPROVED_PEER = 'CUSTOM PEER APPROVED MEMBERSHIPS';
FEED_MEMBERSHIP_FINISH_REJECTED_PEER = 'CUSTOM PEER REJECTED MEMBERSHIPS';

FEED_VOTE_LIVE_CUSTOM = 'live-votes-custom';
*/
