//institutional
ORGANIZATION_NAME = Meteor.settings.public.Collective.name;
ORGANIZATION_ID = Meteor.settings.public.Collective._id;

//text
$LANGUAGE = "en"; //language of the app

//rules
TITLE_MAX_LENGTH = 100; //length of contract titles
MAX_TAGS_PER_CONTRACT = 3; //max amount of tags per contract
MIN_TAGS_PER_CONTRACT = 1; //min amount.
MAX_PROFILE_NAME_LENGTH = 20; //Maximum extension of profile name
VOTES_INITIAL_QUANTITY = 1000; //initial votes for genesis transaction event

//timers
SERVER_INTERVAL = 2500;  //time in ms to communicate with server for contenteditable stuff.
ANIMATION_DURATION = 250; //pace of animations
WARNING_DURATION = 5000; //duration of warning messages

//classes
OFFSCREEN_CLASS = 'off-screen';

//key strings
CURRENCY_BITCOIN = 'BITCOIN';
CURRENCY_SATOSHI = 'SATOSHI';
CURRENCY_VOTES = 'VOTES';
ENTITY_INDIVIDUAL = 'INDIVIDUAL';
ENTITY_COLLECTIVE = 'COLLECTIVE';
ENTITY_CONTRACT = 'CONTRACT';
ENTITY_UNKNOWN = 'UNKNOWN';
KIND_VOTE = 'VOTE';
KIND_DELEGATION = 'DELEGATION';
KIND_MEMBERSHIP = 'MEMBERSHIP';
KIND_UNKNOWN = 'UNKNOWN';
KIND_DRAFT = 'DRAFT';
STATUS_PENDING = 'PENDING';
STATUS_REJECTED = 'REJECTED';
STATUS_CONFIRMED = 'CONFIRMED';
ROLE_DELEGATOR = 'DELEGATOR';
ROLE_DELEGATE = 'DELEGATE';
ROLE_AUTHOR = 'AUTHOR';
ROLE_ENDORSER = 'ENDORSER';
STAGE_DRAFT = 'DRAFT';
STAGE_LIVE = 'LIVE';
STAGE_FINISH = 'FINISH';
THREAD_ACTION_COMMENT = 'COMMENT';
THREAD_ACTION_VOTE = 'VOTE';
THREAD_ACTION_SORT = 'SORT';
THREAD_ACTION_REPLY = 'REPLY';
THREAD_STATUS_NEW = 'NEW';
THREAD_STATUS_VERIFIED = 'VERIFIED';
THREAD_STATUS_PROCESSED = 'PROCESSED';
WALLET_MODE_PENDING = 'PENDING';
WALLET_MODE_EXECUTED = 'EXECUTED';
SIGNATURE_STATUS_PENDING = 'PENDING';
SIGNATURE_STATUS_REJECTED = 'REJECTED';
SIGNATURE_STATUS_CONFIRMED = 'CONFIRMED';
EXECUTION_STATUS_OPEN = 'OPEN';
EXECUTION_STATUS_APPROVED = 'APPROVED';
EXECUTION_STATUS_ALTERNATIVE = 'ALTERNATIVE'
EXECUTION_STATUS_REJECTED = 'REJECTED';
CONTEXT_GLOBAL = 'GLOBAL';
CONTEXT_LOCAL = 'LOCAL';
