// TODO: here we have to implement parser to this https://api.decentraland.org/v1/districts

const _geo = {
  country: [
    {
      code: 'AE',
      emoji: '🎸',
      unicode: '',
      name: 'AETHERIAN project',
      title: '', //
    },
    {
      code: 'VC',
      emoji: '🎭',
      unicode: '',
      name: 'Vegas City',
      title: '', // ',
    },
    {
      code: 'DC',
      emoji: '🐉',
      unicode: '',
      name: 'Dragon City',
      title: '', // ',
    },
    {
      code: 'FS',
      emoji: '💄',
      unicode: '',
      name: 'Fashion Street',
      title: '', // ',
    },
    {
      code: 'X',
      emoji: '⒳',
      unicode: '',
      name: 'District X',
      title: '', // ',
    },
    {
      code: 'DU',
      emoji: '🎓',
      unicode: '',
      name: 'Decentraland University',
      title: '', // ',
    },
    {
      code: 'DK',
      emoji: '🐲',
      unicode: '',
      name: 'Dragon Kingdom',
      title: '', // ',
    },
    {
      code: 'CC',
      emoji: '🌉',
      unicode: '',
      name: 'Decentraland Conference Center',
      title: '', // ',
    },
    {
      code: 'TB',
      emoji: '⚔️',
      unicode: '',
      name: 'The Battleground',
      title: '', // ',
    },
    {
      code: 'VS',
      emoji: '🛍',
      unicode: 'U+1F1E6 U+1F1EB',
      name: 'Virtual Reality Shopping District',
      title: '', // flag for Afghanistan',
    },
    {
      code: 'FL',
      emoji: '🎊',
      unicode: '',
      name: 'Festival Land',
      title: '', // ',
    },
    {
      code: 'TF',
      emoji: '🦌',
      unicode: '',
      name: 'The Forest',
      title: '', // flag for Andorra',
    },
    {
      code: 'CM',
      emoji: '💹',
      unicode: '',
      name: 'Central Marketplace',
      title: '', // flag for United Arab Emirates',
    },
    {
      code: 'CV',
      emoji: '🔑',
      unicode: '',
      name: 'The Crypto Valley',
      title: '', // flag for Afghanistan',
    },
    {
      code: 'CG',
      emoji: '🎡',
      unicode: '',
      name: 'Carnival Games',
      title: '', // flag for Antigua and Barbuda',
    },
    {
      code: 'SP',
      emoji: '🏯',
      unicode: '', //U+1F1E6 U+1F1E9',
      name: 'Shwedagon Pagoda',
      title: '', // flag for Andorra',
    },
    {
      code: 'AA',
      emoji: '💣',
      unicode: '', //U+1F1E6 U+1F1EA',
      name: 'A-Squat',
      title: '', // flag for United Arab Emirates',
    },
    {
      code: 'YT',
      emoji: '🇰🇮',
      unicode: '', //U+1F1E6 U+1F1EB',
      name: 'DPR of Yetepey',
      title: '', // flag for Afghanistan',
    },
    {
      code: 'HC',
      emoji: '👾',
      unicode: '', //U+1F1E6 U+1F1EC',
      name: 'Hacker City',
      title: '', // flag for Antigua and Barbuda',
    },
    {
      code: 'EE',
      emoji: '𝓔',
      unicode: '', //U+1F1E6 U+1F1E9',
      name: 'E for EVERYONE',
      title: '', // flag for Andorra',
    },
    {
      code: 'BT',
      emoji: '📈',
      unicode: '', //',
      name: 'Bittrex Tomorrow',
      title: '', // flag for United Arab Emirates',
    },
    {
      code: 'YO',
      emoji: '🧘‍',
      unicode: '', //',
      name: 'Yoga Center',
      title: '', // flag for Afghanistan',
    },
    {
      code: 'EP',
      emoji: '🤓',
      unicode: '', //U+1F1E6 U+1F1EC',
      name: 'Engineering Park',
      title: '', // ',
    },
    {
      code: 'SC',
      emoji: '🌌',
      unicode: '', //U+1F1E6 U+1F1EC',
      name: 'Star City',
      title: '', // flag for Antigua and Barbuda',
    },
    {
      code: 'VA',
      emoji: '⛩',
      unicode: '', //U+1F1E6 U+1F1EC',
      name: 'VARC All things Architecture',
      title: '', // flag for Antigua and Barbuda',
    },
    {
      code: 'DQ',
      emoji: '✍️',
      unicode: '', //U+1F1E6 U+1F1EC',
      name: 'Design Quarter',
      title: '', // flag for Antigua and Barbuda',
    },
    {
      code: 'CH',
      emoji: '🤚',
      unicode: '', //U+1F1E6 U+1F1EC',
      name: 'Chobury City',
      title: '', // flag for Antigua and Barbuda',
    },
    {
      code: 'EG',
      emoji: '🌍',
      unicode: '', //U+1F1E6 U+1F1EC',
      name: 'EcoGames',
      title: '', // flag for Antigua and Barbuda',
    },
    {
      code: 'AN',
      emoji: '🏴',
      unicode: '', //U+1F1E6 U+1F1EC',
      name: 'Anarchy',
      title: '', // flag for Antigua and Barbuda',
    },
    {
      code: 'VO',
      emoji: '🦹',
      unicode: '', //U+1F1E6 U+1F1EC',
      name: 'Voltaire',
      title: '', // flag for Antigua and Barbuda',
    },
    {
      code: 'HD',
      emoji: '🦌',
      unicode: '', //U+1F1E6 U+1F1EC',
      name: 'Hunted District',
      title: '', // flag for Antigua and Barbuda',
    },
    {
      code: 'TS',
      emoji: '🍩',
      unicode: '', //U+1F1E6 U+1F1EC',
      name: 'Toke Social Cannabis',
      title: '', // flag for Antigua and Barbuda',
    },
    {
      code: 'MH',
      emoji: '👨‍🎤',
      unicode: '', //U+1F1E6 U+1F1EC',
      name: 'MusicHub',
      title: '', // flag for Antigua and Barbuda',
    },
    {
      code: 'CC',
      emoji: '🇨🇳',
      unicode: '', //U+1F1E6 U+1F1EC',
      name: 'DCL China City',
      title: '', // flag for Antigua and Barbuda',
    },
    {
      code: 'DM',
      emoji: '🗿',
      unicode: '', //U+1F1E6 U+1F1EC',
      name: 'Decentraland Museum',
      title: '', // flag for Antigua and Barbuda',
    },
    {
      code: 'AF',
      emoji: '🏟',
      unicode: '', //U+1F1E6 U+1F1EC',
      name: 'Arena',
      title: '', // flag for Antigua and Barbuda',
    },
    {
      code: 'FD',
      emoji: '🧸',
      unicode: '', // U+1F1E6 U+1F1EC',
      name: 'Fluffy DC',
      title: '', // flag for Antigua and Barbuda',
    },
  ],
};

export const geo = _geo;
