const _token = {
  coin: [
    {
      code: 'AE',
      emoji: '',
      unicode: '',
      name: 'Aeternity',
      title: 'Scalable smart contracts interfacing with real world data.',
    },
    {
      code: 'AION',
      emoji: '',
      unicode: '',
      name: 'AION',
      title: 'A multi-tier blockchain system designed to address unsolved questions of scalability, privacy, and interoperability in blockchain networks.',
    },
    {
      code: 'REP',
      emoji: '',
      unicode: '',
      name: 'Augur',
      title: 'Augur combines the magic of prediction markets with the power of a decentralized network to create a stunningly accurate forecasting tool.',
    },
    {
      code: 'BNT',
      emoji: '',
      unicode: '',
      name: 'Bancor',
      title: 'Bancor Protocol is a standard for a new generation of cryptocurrencies called Smart Tokens.',
    },
    {
      code: 'BAT',
      emoji: '',
      unicode: '',
      name: 'Basic Attention Token',
      title: 'The Basic Attention Token is the new token for the digital advertising industry.',
    },
    {
      code: 'BNB',
      emoji: '',
      unicode: '',
      name: 'Binance',
      title: 'Binance aims to build a world-class crypto exchange, powering the future of crypto finance.',
    },
    {
      code: 'BIX',
      emoji: '',
      unicode: '',
      name: 'BIX Token',
      title: 'AI Enhanced Encrypted Digital Asset Exchange.',
    },
    {
      code: 'BTM',
      emoji: '',
      unicode: '',
      name: 'Bytom',
      title: 'Transfer assets from atomic world to byteworld.',
    },
    {
      code: 'CENNZ',
      emoji: '',
      unicode: '',
      name: 'Centrality Token',
      title: 'Centrality Token',
    },
    {
      code: 'CTXC',
      emoji: '',
      unicode: '',
      name: 'Cortex Coin',
      title: 'Decentralized AI autonomous system.',
    },
    {
      code: 'CMT',
      emoji: '',
      unicode: '',
      name: 'CyberMiles',
      title: 'Empowering the Decentralization of Online Marketplaces.',
    },
    {
      code: 'MANA',
      emoji: '',
      unicode: '',
      name: 'Decentraland',
      title: 'Decentraland is a virtual reality platform powered by the Ethereum blockchain. Users can create, experience, and monetize content and applications.',
    },
    {
      code: 'Dentacoin',
      emoji: '',
      unicode: '',
      name: 'Dentacoin',
      title: 'Aims to be the blockchain solution for the global dental industry.',
    },
    {
      code: 'DGD',
      emoji: '',
      unicode: '',
      name: 'DigixDAO',
      title: 'DigixDAO is a decentralized voting / utility token that allows users to submit and manage proposals that relate to the growth of the Digix ecosystem and platform.',
    },
    {
      code: 'ELF',
      emoji: '',
      unicode: '',
      name: 'ELF',
      title: 'Decentralized Cloud Computing Blockchain Network.',
    },
    {
      code: 'ENG',
      emoji: '',
      unicode: '',
      name: 'Enigma',
      title: 'Enigma is a privacy protocol that enables truly decentralized applications and unlocks the value of blockchains.',
    },
    {
      code: 'ETHOS',
      emoji: '',
      unicode: '',
      name: 'Ethos',
      title: 'People-powered cryptocurrency services for the blockchain.',
    },
    {
      code: 'FUN',
      emoji: '',
      unicode: '',
      name: 'FunFair',
      title: 'FunFair is a decentralised gaming platform powered by Ethereum smart contracts.',
    },
    {
      code: 'GTC',
      emoji: '',
      unicode: '',
      name: 'Game.com',
      title: 'Game.com is focused on creating a global gaming platform for blockchain digital currencies.',
    },
    {
      code: 'GTO',
      emoji: '',
      unicode: '',
      name: 'Gifto',
      title: 'Decentralized Universal Gifting Protocol.',
    },
    {
      code: 'GNT',
      emoji: '',
      unicode: '',
      name: 'Golem',
      title: 'Golem is going to create the first decentralized global market for computing power.',
    },
    {
      code: 'HT',
      emoji: '',
      unicode: '',
      name: 'Huobi Token',
      title: 'Huobi Global is a world-leading cryptocurrency financial services group.',
    },
    {
      code: 'ICX',
      emoji: '',
      unicode: '',
      name: 'ICON',
      title: 'The ICON Network is comprised of various institutions ranging from: financial institutions, insurance companies, hospitals, universities and more.',
    },
    {
      code: 'IOST',
      emoji: '',
      unicode: '',
      name: 'IOSToken',
      title: 'A Secure & Scalable Blockchain for Smart Services.',
    },
    {
      code: 'KIN',
      emoji: '',
      unicode: '',
      name: 'Kin',
      title: 'The vision for Kin is rooted in the belief that a broad group of participants can come together to create an open ecosystem of tools for digital communication and commerce that prioritizes consumer experience, bringing a fair and user-oriented model for digital services to the market.',
    },
    {
      code: 'KNC',
      emoji: '',
      unicode: '',
      name: 'Kyber Network',
      title: 'KyberNetwork is a new system which allows the exchange and conversion of digital assets.',
    },
    {
      code: 'LOOM',
      emoji: '',
      unicode: '',
      name: 'Loom',
      title: 'Online game & social apps.',
    },
    {
      code: 'LRC',
      emoji: '',
      unicode: '',
      name: 'Loopring',
      title: 'Loopring is not only a protocol but also a decentralized automated execution system that trades across the crypto-token exchanges.',
    },
    {
      code: 'MKR',
      emoji: '',
      unicode: '',
      name: 'Maker',
      title: 'Maker is a Decentralized Autonomous Organization that creates and insures the dai stablecoin on the Ethereum blockchain.',
    },
    {
      code: 'MCO',
      emoji: '',
      unicode: '',
      name: 'Monaco',
      title: 'Monaco is a cryptocurrency card. Spend and send money globally at interbank exchange rates.',
    },
    {
      code: 'NAS',
      emoji: '',
      unicode: '',
      name: 'Nebulas',
      title: 'Decentralized Search Framework.',
    },
    {
      code: 'NULS',
      emoji: '',
      unicode: '',
      name: 'Nuls',
      title: 'NULS is a global blockchain open-source project which is a highly customizable modular blockchain infrastructure consisting of a microkernel and functional modules.',
    },
    {
      code: 'OMG',
      emoji: '',
      unicode: '',
      name: 'OmiseGO',
      title: 'OmiseGO is a public Ethereum-based financial technology for use in mainstream digital wallets.',
    },
    {
      code: 'POLY',
      emoji: '',
      unicode: '',
      name: 'Polymath',
      title: 'Polymath aims to enable securities to migrate to the blockchain.',
    },
    {
      code: 'PPT',
      emoji: '',
      unicode: '',
      name: 'Populous',
      title: 'Aims to rebuild invoice financing block by block, for invoice buyers and sellers.',
    },
    {
      code: 'POWR',
      emoji: '',
      unicode: '',
      name: 'PowerLedger',
      title: 'Power Ledger is a peer-to-peer marketplace for renewable energy.',
    },
    {
      code: 'QASH',
      emoji: '',
      unicode: '',
      name: 'QASH',
      title: 'We envision QASH to be the preferred payment token for financial services, like the Bitcoin for financial services. As more financial institutions, fintech startups and partners adopt QASH as a method of payment, the utility of QASH will scale, fueling the Fintech revolution.',
    },
    {
      code: 'RHOC',
      emoji: '',
      unicode: '',
      name: 'RChain',
      title: 'The RChain Platform aims to be a decentralized, economically sustainable public compute infrastructure.',
    },
    {
      code: 'SNT',
      emoji: '',
      unicode: '',
      name: 'Status Network',
      title: 'Status is an open source messaging platform and mobile browser to interact with decentralized applications that run on the Ethereum Network.',
    },
    {
      code: 'STORM',
      emoji: '',
      unicode: '',
      name: 'Storm',
      title: 'Storm Market aims to make it easier for members to find new ways to earn, engage, and advance with their gamified micro-task platform for STORM tokens.',
    },
    {
      code: 'SUB',
      emoji: '',
      unicode: '',
      name: 'Substratum',
      title: 'Substratum is an open-source network that allows anyone to allocate spare computing resources to make the internet a free and fair place for the entire world.',
    },
    {
      code: 'THETA',
      emoji: '',
      unicode: '',
      name: 'Theta',
      title: 'A decentralized peer-to-peer network that aims to offer improved video delivery at lower costs.',
    },
    {
      code: 'TRX',
      emoji: '',
      unicode: '',
      name: 'TRON',
      title: 'TRON is a blockchain-based decentralized protocol that aims to construct a worldwide free content entertainment system with the blockchain and distributed storage technology.',
    },
    {
      code: 'TUSD',
      emoji: '',
      unicode: '',
      name: 'TrueUSD',
      title: 'The TrustToken Platform aims to be the bridge between blockchains and real-world assets.',
    },
    {
      code: 'VEN',
      emoji: '',
      unicode: '',
      name: 'VeChain',
      title: 'VeChain aims to connect blockchain technology to the real world by providing a comprehensive governance structure, a robust economic model as well as advanced IoT integration.',
    },
    {
      code: 'VERI',
      emoji: '',
      unicode: '',
      name: 'Veritaseum',
      title: 'Veritaseum builds blockchain-based, peer-to-peer capital markets as software on a global scale.',
    },
    {
      code: 'WTC',
      emoji: '',
      unicode: '',
      name: 'Walton',
      title: 'Value Internet of Things (VIoT) constructs a perfect commercial ecosystem via the integration of the real world and the blockchain.',
    },
    {
      code: 'WAX',
      emoji: '',
      unicode: '',
      name: 'WAX',
      title: 'Global Decentralized Marketplace for Virtual Assets.',
    },
    {
      code: 'ZIL',
      emoji: '',
      unicode: '',
      name: 'Zilliqa',
      title: 'Zilliqa is a high-throughput public blockchain platform - designed to scale to thousands ​of transactions per second.',
    },
    {
      code: 'ZRX',
      emoji: '',
      unicode: '',
      name: 'ZRX',
      title: 'The Protocol for Trading Tokens.',
    },
  ],
};

export const token = _token;
