const _token = {
  coin: [
    {
      code: 'ANT',
      emoji: '',
      unicode: '',
      name: 'Aragon',
      title: 'Unstoppable organizations.',
    },
    {
      code: 'REP',
      emoji: '',
      unicode: '',
      name: 'Augur',
      title: 'Augur combines the magic of prediction markets with the power of a decentralized network to create a stunningly accurate forecasting tool.',
    },
    {
      code: 'BNT',
      emoji: '',
      unicode: '',
      name: 'Bancor',
      title: 'Bancor Protocol is a standard for a new generation of cryptocurrencies called Smart Tokens.',
    },
    {
      code: 'BAT',
      emoji: '',
      unicode: '',
      name: 'Basic Attention Token',
      title: 'The Basic Attention Token is the new token for the digital advertising industry.',
    },
    {
      code: 'STACK',
      emoji: '',
      unicode: '',
      name: 'Blockstack',
      title: 'Decentralized applications.',
      color: 'rgb(236, 22, 97)',
    },
    {
      code: 'BNB',
      emoji: '',
      unicode: '',
      name: 'Binance',
      title: 'Binance aims to build a world-class crypto exchange, powering the future of crypto finance.',
    },
    {
      code: 'BTC',
      emoji: '',
      unicode: '',
      name: 'Bitcoin',
      title: 'Bitcoin blockchain.',
      color: '#f7931a',
    },
    {
      code: 'BCH',
      emoji: '',
      unicode: '',
      name: 'Bitcoin Cash',
      title: 'Bitcoin blockchain fork: Bitcoin Cash.',
      color: '#4ac846',
    },
    {
      code: 'MANA',
      emoji: '',
      unicode: '',
      name: 'Decentraland',
      title: 'Decentraland is a virtual reality platform powered by the Ethereum blockchain. Users can create, experience, and monetize content and applications.',
    },
    {
      code: 'ETH',
      emoji: '',
      unicode: '',
      name: 'Ethereum',
      title: 'Ethereum blockchain.',
      color: '#7885cb',
    },
    {
      code: 'ETC',
      emoji: '',
      unicode: '',
      name: 'Ethereum Classic',
      title: 'Original Ethereum blockchain.',
      color: '#3ab83a',
    },
    {
      code: 'EOS',
      emoji: '',
      unicode: '',
      name: 'EOS',
      title: 'EOS Delegated Proof of Stake blockchain.',
      color: '#000',
    },
    {
      code: 'GNT',
      emoji: '',
      unicode: '',
      name: 'Golem',
      title: 'Golem is going to create the first decentralized global market for computing power.',
    },
    {
      code: 'LOOM',
      emoji: '',
      unicode: '',
      name: 'Loom',
      title: 'Online game & social apps.',
    },
    {
      code: 'OMG',
      emoji: '',
      unicode: '',
      name: 'OmiseGO',
      title: 'OmiseGO is a public Ethereum-based financial technology for use in mainstream digital wallets.',
    },
    {
      code: 'SNT',
      emoji: '',
      unicode: '',
      name: 'Status Network',
      title: 'Status is an open source messaging platform and mobile browser to interact with decentralized applications that run on the Ethereum Network.',
    },
    {
      code: 'TRX',
      emoji: '',
      unicode: '',
      name: 'TRON',
      title: 'TRON is a blockchain-based decentralized protocol that aims to construct a worldwide free content entertainment system with the blockchain and distributed storage technology.',
    },
    {
      code: 'VOTE',
      emoji: '',
      unicode: '',
      name: 'Democracy Earth',
      title: 'Universal Basic Income for valid citizens of the Democracy Earth Network.',
      color: '#00c091',
    },
    {
      code: 'ZEP',
      emoji: '',
      unicode: '',
      name: 'Zeppelin',
      title: 'Smart contract auditing.',
    },
  ],
};

export const token = _token;
